include:
  - ../_common/networks.yaml

services:
  # HOMEPAGE
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_FILE_BAZARR_KEY: /run/secrets/bazarr_key
      HOMEPAGE_FILE_PROWLARR_KEY: /run/secrets/prowlarr_key
      HOMEPAGE_FILE_RADARR_KEY: /run/secrets/radarr_key
      HOMEPAGE_FILE_SONARR_KEY: /run/secrets/sonarr_key
      HOMEPAGE_FILE_OPENWRT_USER: /run/secrets/openwrt_user
      HOMEPAGE_FILE_OPENWRT_PASS: /run/secrets/openwrt_pass
      HOMEPAGE_FILE_QBITTORRENT_USER: /run/secrets/qbittorrent_user
      HOMEPAGE_FILE_QBITTORRENT_PASS: /run/secrets/qbittorrent_pass
      HOMEPAGE_FILE_JELLYFIN_KEY: /run/secrets/jellyfin_key
      HOMEPAGE_FILE_JELLYSEERR_KEY: /run/secrets/jellyseerr_key
    volumes:
      - /var/docker/homepage/config:/app/config
    restart: unless-stopped
    networks:
      - default
      - homelab
    secrets:
      - bazarr_key
      - prowlarr_key
      - radarr_key
      - sonarr_key
      - openwrt_user
      - openwrt_pass
      - qbittorrent_user
      - qbittorrent_pass
      - jellyfin_key
      - jellyseerr_key

  # DOCKER PROXY
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homepage-dockerproxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

secrets:
  bazarr_key:
    file: ./secrets/bazarr_key
  prowlarr_key:
    file: ./secrets/prowlarr_key
  radarr_key:
    file: ./secrets/radarr_key
  sonarr_key:
    file: ./secrets/sonarr_key
  openwrt_user:
    file: ./secrets/openwrt_user
  openwrt_pass:
    file: ./secrets/openwrt_pass
  qbittorrent_user:
    file: ./secrets/qbittorrent_user
  qbittorrent_pass:
    file: ./secrets/qbittorrent_pass
  jellyfin_key:
    file: ./secrets/jellyfin_key
  jellyseerr_key:
    file: ./secrets/jellyseerr_key

networks:
  default:
