- Calendar:
      - "":
            widget:
                type: calendar
                firstDayInWeek: sunday # optional - defaults to monday
                view: monthly # optional - possible values monthly, agenda
                maxEvents: 10 # optional - defaults to 10
                showTime: true # optional - show time for event happening today - defaults to false
                timezone: America/Sao_Paulo # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
                integrations: # optional
                    - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
                      service_group: Media # group name where widget exists
                      service_name: Sonarr # service name for that widget
                      #   color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
                      params: # optional - additional params for the service
                          unmonitored: true # optional - defaults to false, used with *arr stack
                    - type: radarr
                      service_group: Media
                      service_name: Radarr
                      #   color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
                      params: # optional - additional params for the service
                          unmonitored: true # optional - defaults to false, used with *arr stack
- Media:
      - Jellyfin:
            icon: sh-jellyfin
            href: "http://jellyfin.youngrobot.lan"
            server: youngrobot
            container: jellyfin
            widget:
                type: jellyfin
                url: "http://jellyfin:8096"
                key: {{HOMEPAGE_FILE_JELLYFIN_KEY}}
                enableBlocks: true
                enableNowPlaying: true
                enableUser: true
                showEpisodeNumber: true
                expandOneStreamToTwoRows: false
      - Sonarr:
            icon: sh-sonarr
            href: "http://sonarr.youngrobot.lan"
            server: youngrobot
            container: sonarr
            widget:
              type: sonarr
              url: "http://sonarr:8989"
              key: {{HOMEPAGE_FILE_SONARR_KEY}}
      - Radarr:
            icon: sh-radarr-light
            href: "http://radarr.youngrobot.lan"
            server: youngrobot
            container: radarr
            widget:
                type: radarr
                url: "http://radarr:7878"
                key: {{HOMEPAGE_FILE_RADARR_KEY}}      
- Services:
      - Bazarr:
            icon: sh-bazarr
            href: "http://bazarr.youngrobot.lan"
            server: youngrobot
            container: bazarr
            widget:
                type: bazarr
                url: "http://bazarr:6767"
                key: {{HOMEPAGE_FILE_BAZARR_KEY}}
      - Prowlarr:
            icon: sh-prowlarr
            href: http://prowlarr.youngrobot.lan
            server: youngrobot
            container: prowlarr
            widget:
                type: prowlarr
                url: http://prowlarr:9696
                key: {{HOMEPAGE_FILE_PROWLARR_KEY}}
      - Jellyseerr:
            icon: sh-jellyseerr
            href: "http://jellyseerr.youngrobot.lan"
            server: youngrobot
            container: jellyseerr
            widget:
                type: jellyseerr
                url: "http://jellyseerr:5055"
                key: {{HOMEPAGE_FILE_JELLYSEERR_KEY}}
      - Qbittorrent:
            icon: qbittorrent
            href: "http://qbittorrent.youngrobot.lan"
            server: youngrobot
            container: qbittorrent
            widget:
                type: qbittorrent
                url: "http://qbittorrent:8080"
                username: {{HOMEPAGE_FILE_QBITTORRENT_USER}}
                password: {{HOMEPAGE_FILE_QBITTORRENT_PASS}}

- Data & Network:
      - OpenWrt:
            icon: openwrt
            href: "http://192.168.1.1"
            widget:
                type: openwrt
                url: "http://192.168.1.1"
                username: {{HOMEPAGE_FILE_OPENWRT_USER}}
                password: {{HOMEPAGE_FILE_OPENWRT_PASS}}
                interfaceName: eth0
