include:
  - ../_common/networks.yaml

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    volumes:
      - /var/docker/nginx/config:/etc/nginx/conf.d/:ro
    networks:
      - homelab
    healthcheck:
      test: curl --fail http://localhost/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
